---
title: "Untitled"
author: "Bas Machielsen"
date: "28-2-2020"
output:
  pdf_document: 
    includes:
            in_header: header.tex 
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE, warning = FALSE, include = FALSE}
library(readxl)
library(tidyverse)
library(hrbrthemes)
```

## Import data
```{r}
data <- read_excel("Copy of Cotton-mills-wage-data-detailed.xlsx", 
                   sheet = 2)
```

## Here I reshape the data so that ggplot will treat it
```{r}
data <- data %>%
    pivot_longer(cols = 2:24, 
                 names_to = "year", 
                 values_to = "rate")
```


Very important equation:

\begin{equation}
E = mc^{2-i}
\end{equation}

## Here I filter the data to exclude the categories mentioned below
```{r}
data2 <- data %>%
    filter(Classes != "Average female wages", 
           Classes != "Average male wages",
           Classes != "gender wage gap (f/m)")
```

## Here I specify the data which I want to use to generate the names
```{r}
test <- data %>%
    group_by(year) %>%
    mutate(cutoffpos = mean(rate, na.rm=TRUE) + 1.5*IQR(rate, na.rm = TRUE),
           minimum = min(rate, na.rm = TRUE)) %>%
    filter(rate >= cutoffpos | rate == minimum )
```

## Here I make figure 1
```{r}
figure1 <- ggplot(data2, aes(x = year, 
                             y = rate))  + 
    geom_boxplot() + 
    geom_text(test, 
              mapping = aes(
                  x = year, 
                  y = rate, 
                  label = Classes),
              size = 3) +
    coord_flip() +
    theme_classic() +
    ggtitle("hello!") + # In this line, you change the title
    xlab("Year") + 
    ylab("Rate")
ggsave("figure1.png", figure1)

figure1
```


## Here I make figure 2

\newpage
\blandscape

```{r}
figure2 <- ggplot(data2, aes(x = Classes, 
                             y = rate, 
                             fill = Classes)) + 
    geom_boxplot() +
    theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggsave("figure2.png", figure2)

figure2
```

\elandscape